### PR TITLE
remove check for forcing csv files

### LINKED ISSUE #238: Error when running in parallel mode with AWI_16_2863657_007 input data on Windows
While running ngiab in parallel mode with AWI_16_2863657_007 input data on Windows, it causes a floating-point exception during the partitioning step.

## Current behavior
During the partitioning step, it logs: `Partitioning 241 catchments into 0 partitions` and throws a floating-point exception.
## Expected behavior
It should partition the catchments correctly and run the model in parallel mode without errors.

## Steps to replicate behavior (include URLs)

**Step 1: Create Project Directory**

-  Open WSL with administrator privileges and execute:
```bash
cd /mnt/c/Users/
ls
cd <User Folder>
```

```bash
mkdir -p NextGen/ngen-data
```

```bash
cd NextGen/ngen-data
```
**Step 2: Download Sample Data**

-  Use wget to download the compressed data file:
```bash
wget --no-parent https://ciroh-ua-ngen-data.s3.us-east-2.amazonaws.com/AWI-007/AWI_16_2863657_007.tar.gz
```

**Step 3: Extract and Rename**

-  Extract the downloaded file and optionally rename the folder:
```bash
tar -xf AWI_16_2863657_007.tar.gz
```
```bash
mv AWI_16_2863657_007 my_data
```

**Step 3: Clone the Repository:**
Go to the folder created earlier during step 1 above

```bash
cd NextGen
```
```bash
git clone https://github.com/CIROH-UA/NGIAB-CloudInfra.git
```
```bash
cd NGIAB-CloudInfra
```

**Step 5: Run the Guide :**
```bash
./guide.sh
```
If you encounter a 401 Unauthorized error, re-run the script:
```bash
sudo ./guide.sh
```
**Step 6: Follow the prompts:**
    - **Input Data Path:** Enter the path to your downloaded or generated input data directory. (e.g NextGen/ngen-data/my_data)
    - **Run Mode:** Choose to run ngiab in parallel mode.

## Screenshots
Screenshot 2024-11-25 160240

### PR DESCRIPTION
**Pull request by JoshCu**
fixes #238

### CODE REVIEW

**Comment by manjilasingh** [comment]
I tested the changes but i am still getting the same error

image

**Comment by JoshCu** [comment]
> I tested the changes but i am still getting the same error
> 
> image

Did you rebuild the docker image to test it? The hellongen script is inside the docker container so it won't be updated unless the image is rebuilt.

You could test it manually though which would probably be easier. Run the guide script as normal but select 3 to run the bash shell.
You can then modify the script with `vim /ngen/HelloNGEN.sh`
Then while still on the bash shell, run `/ngen/HelloNGEN.sh /ngen/ngen/data` to continue running the modified script

**Comment by benlee0423** [comment]
@manjilasingh 
Build is running now. And I will let you know if it is done, and instructions to run it.
Stay tuned.

**Comment by manjilasingh** [comment]
I tested it again with the rebuilt Docker image, and it works now.

**Comment by benlee0423** [comment]
Thank you @JoshCu  for quick fix.

**Pull request merged**
