### PR TITLE
run the ngen image build/test on PR's to main and pr-merge branches

### PR DESCRIPTION
**Pull request by hellkite500**
Trigger ngen image build aciton on PR.  This can probably be refined a little bit, but will test PR's on this repo to ensure the main ngen image builds with proposed changes.

Possibly related to #49

### CODE REVIEW

**Comment by benlee0423** [comment]
I don't think this will work. We are working on it to handle this.
Thank you.

**Comment by hellkite500** [comment]
Care to elaborate as to why you don't think this will work?

**Comment by hellkite500** [comment]
Other than the checks being "Skipped", this is getting towards the desired outcome -- running the test/workflow on PR's...

image

**Comment by benlee0423** [comment]
Best practice: 
Run actions on PR.

Here:
We want to run it manually.

**Comment by arpita0911patel** [comment]
Closing this PR as this is taken care by https://github.com/CIROH-UA/NGIAB-CloudInfra/pull/74 (CI changes)

**Pull request closed without merging**
