### PR TITLE
Update Dockerfile.ngen to add NGEN_WITH_SQLITE: ON

### PR DESCRIPTION
**Pull request by ZacharyWills**
Related to #63 

For Testing gpkg support in NGIAB

### CODE REVIEW

**Comment by ZacharyWills** [comment]
Screenshot 2024-01-03 at 22 20 52

I'm making progress, just missing something somewhere

**Comment by benlee0423** [comment]
@ZacharyWills 
Is this working?

**Comment by arpita0911patel** [comment]
I tested this PR with the image created i.e. :latest-PR tag, and it seems like not working. NGEN_WITH_SQLITE: OFF

**bash-5.1# /dmod/bin/ngen --info**
NGen version: 0.1.0
Build configuration summary:
  Generator: Unix Makefiles
  Build type: 
  System: Linux
  C Compiler: /usr/bin/cc
  CXX Compiler: /usr/bin/c++
  Flags:
    NGEN_WITH_MPI: ON
    NGEN_WITH_NETCDF: ON
    **NGEN_WITH_SQLITE: OFF**
    NGEN_WITH_UDUNITS: ON
    NGEN_WITH_BMI_FORTRAN: ON
    NGEN_WITH_BMI_C: ON
    NGEN_WITH_PYTHON: ON
    NGEN_WITH_ROUTING: ON
    NGEN_WITH_TESTS: ON
    NGEN_QUIET: OFF

**Comment by arpita0911patel** [comment]
According to Zach, the image works fine when built locally. Therefore, it seems that further investigation is required.

**Comment by benlee0423** [comment]
One thing I can think of is no-cache option during build.
@ZacharyWills 
Can you build with no-cache=true locally and see if it produces the same error with new image built on runner?

**Comment by ZacharyWills** [comment]
> One thing I can think of is no-cache option during build. @ZacharyWills Can you build with no-cache=true locally and see if it produces the same error with new image built on runner?

It doesn't, when built locally with --no-cache it builds fine. It's only an issue when built by the runner.

**Comment by benlee0423** [comment]
I have removed all caches from Runner.

**Comment by arpita0911patel** [comment]
Ben, please let us know when you rerunun the CI against this PR.

**Comment by benlee0423** [comment]
It is building now.
I had to merge changes in main to this branch to build.

**Comment by benlee0423** [comment]
github is not very good at diff.
Just look at Dockerfile.ngen and Dockerfile.ngen-deps for review and merge. It is safe to ignore the other files.

**Comment by benlee0423** [comment]
Build failed.
```
32.21   Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
32.21 Call Stack (most recent call first):
32.21   /usr/local/lib64/python3.9/site-packages/cmake/data/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
32.21   /usr/local/lib64/python3.9/site-packages/cmake/data/share/cmake-3.28/Modules/FindSQLite3.cmake:54 (find_package_handle_standard_args)
```

**Comment by benlee0423** [comment]
@arpita0911patel @ZacharyWills 
DO NOT merge this PR. I messed up the files, and those are not showing diff correctly with main. I will have to create a new PR for this.
Test was successful. See my comments on the issue #63

**Comment by benlee0423** [comment]
Opend #79

**Comment by arpita0911patel** [comment]
Closing this one as #79 is opened for the same.

**Pull request closed without merging**
