### PR TITLE
Add instructions to build image locally

### PR DESCRIPTION
**Pull request by benlee0423**

### CODE REVIEW

**Comment by benlee0423** [comment]
@manjilasingh 
Can you run this build instructions added in windows machine, and let's update here if it works?

**Comment by manjilasingh** [comment]
@benlee0423 
Screenshot 2024-07-10 104250
I got this error for the first build. i had to use sudo to fix it. the other image builds worked fine

**Comment by benlee0423** [comment]
@manjilasingh 
It looks like it is transient error because it said SSL error.
I assume you run this in WSL in windows. If you did not run WSL as administrator, can you do this again with as an administrator?

**Comment by manjilasingh** [comment]
@benlee0423 That fixed the error. All the other builds work too.

**Comment by benlee0423** [comment]
@manjilasingh 
Great!
Thank you for confirming!

**Review by arpita0911patel — APPROVED** [review]
Looks good.

**Pull request merged**
