### PR TITLE
Fix PR from forked branch

### PR DESCRIPTION
**Pull request by benlee0423**
Requirement from Issue [86](https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/86):
On a pull request, the pipeline will build and run tests using the container on the runner in auto mode and sample test data. On merge to the main branch, the pipeline will build and push the Docker image to DockerHub.

What is included in this PR:
1. Fix action launch on PR from forked branch
2. Start and Stop Runner is disabled for X86 build.
3. Add separate workflow for X86 build, and this is manual build.

What is NOT included in this PR:
1. New [build-and-test](https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/x86-build/.github/action_templates/build-and-test/action.yaml) action is just place holder, and it will be replaced with build and run tests in issue [89](https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/89) later.

Note: PR from forked branch needs to start/stop Runner manually for security reason all time.

### CODE REVIEW

**Review by arpita0911patel — COMMENTED** [review]
Thank you @benlee0423 for working on these CI pipeline changes. Great work indeed!! I'm reviewing it now and will let you know if anything. Additional testing will be done once the PRs are submitted using forked branches. Also adding @hellkite500 and @ZacharyWills for final review.

**Comment by benlee0423** [comment]
> Can you clarify at a high level what these workflow changes do when a PR is created?

See updated description of this PR, and requirement section.

**Comment by benlee0423** [comment]
> these are still attempting to do a complete end-to-end build, push, test workflow for every PR

No, on PR it will do build and test ( with auto-mode running with fixed input data).
New action is just place holder for now, because setting `push: false` in action does not create docker image on the Runner, as a result all subsequent builds failed. `push: false` will be replaced with `load: true`.

**Comment by benlee0423** [comment]
> still requires manual engagement of the runner to perform any testing of a PR from an external source

We will be using fixed source ( files on the Runner) and auto-mode running. There will be no manual engagement.

**Comment by benlee0423** [comment]
Updated PR description for clarification.

**Comment by arpita0911patel** [comment]
Merging it to test it works for the forked PRs and then if any issues we can fix it after that.

**Pull request merged**
