### PR TITLE
Pin pyarrow install to avoid ngen integration issues

### PR DESCRIPTION
**Pull request by hellkite500**
Issues in pyarrow and arrows upstream prevent us from using v12.0.0 or greater at this point.  This PR will ensure a compatible version is used in the dockerfile.

### CODE REVIEW

**Comment by arpita0911patel** [comment]
The build is successful with these modifications. However, during testing with the guide.sh script and AWI_03W_113060_001.tar.gz, an error persists, indicating "At declaration of smc_profile size, soil_reservoir.n_soil_layers = 0
Using Routing
./HelloNGEN.sh: line 76:    13 Segmentation fault      /dmod/bin/ngen-serial $n1 all $n2 all $n3"

**Comment by benlee0423** [comment]
That's the same error I got from past commits in ngen repo.

**Comment by arpita0911patel** [comment]
Based on the discussion today morning with Nels, Trupesh, Ben, and James we agreed to merge the PR#40,45,47.

**Comment by benlee0423** [comment]
Only PR #45 and #47 are merged on #58.
This merge is not necessary after discussion with everyone. Closing this PR.

**Pull request closed without merging**
