### PR TITLE
Dockerfile fix

### PR DESCRIPTION
**Pull request by JoshCu**
- Locks cython version to 0.29.36
- makes duplicate ngen cmake args into one list of common args
- uses absolute paths instead of ${workdir} relative

## Todo
- [x] Build and test on an arm64 machine

## Testing
On an x86 ubuntu-server 22.04 machine the dockerfiles build and guide.sh ran 
All local, none of this was pushed to dockerhub.
```bash
 docker build -t awiciroh/ngen-deps -f Dockerfile.ngen-deps .
 docker build -t awiciroh/t-route -f Dockerfile.t-route .
 docker build -t awiciroh/ngen -f Dockerfile.ngen .
 docker build -t awiciroh/ciroh-ngen-image:latest-x86 -f Dockerfile .
cd ..
./guide.sh
```
image

### CODE REVIEW

**Comment by arpita0911patel** [comment]
Hi Josh, I tried to build and test these changes on arm64 machine and still getting the same segmentation fault issue. `At declaration of smc_profile size, soil_reservoir.n_soil_layers = 0
Using Routing
./HelloNGEN.sh: line 76:    13 Segmentation fault      /dmod/bin/ngen-serial $n1 all $n2 all $n3
apatel54@UA-W2RP43G:~/NextGen/NGIAB-CloudInfra|dockerfile_fix⚡ ⇒  
`

**Comment by ZacharyWills** [comment]
Attempting to recreate on ARM from Josh's directions here:  
```
docker build -t awiciroh/ngen-deps -f Dockerfile.ngen-deps .
 docker build -t awiciroh/t-route -f Dockerfile.t-route .
 docker build -t awiciroh/ngen -f Dockerfile.ngen .
 docker build -t awiciroh/ciroh-ngen-image:latest-x86 -f Dockerfile .
cd ..
./guide.sh
```
Will document any issues I get if the seg faults happen for this PR branch as well.

**Comment by JoshCu** [comment]
I'm now getting the segfault on x86 too.

This seems to be a bit of a moving target with these dockerfiles as they just clone the latest version of troute.
I also noticed docker using the cached git clone step so it was pulling some random troute commit from whenever I last ran that step uncached.

## Reproducing the error
First modify guide.sh to use a local image, my final tag is joshcu/ngiab-dev so I have
```shell
#if uname -a | grep arm64 || uname -a | grep aarch64 ; then

#docker pull awiciroh/ciroh-ngen-image:latest-arm
#echo -e "Pulled awiciroh/ciroh-ngen-image:latest-arm image"
#IMAGE_NAME=awiciroh/ciroh-ngen-image:latest-arm
#else

#docker pull awiciroh/ciroh-ngen-image:latest-x86
#echo -e "Pulled awiciroh/ciroh-ngen-image:latest-x86 image"
#IMAGE_NAME=awiciroh/ciroh-ngen-image:latest-x86
#fi

IMAGE_NAME=joshcu/ngiab-dev
```
sidenote: I think docker automatically pulls the image based on arch, so we can upload two "latest" tagged images, one for x86, one for arm.
```shell
docker build -t awiciroh/ngen-deps -f Dockerfile.ngen-deps . --no-cache &&/
docker build -t awiciroh/t-route -f Dockerfile.t-route . --no-cache &&/
docker build -t awiciroh/ngen -f Dockerfile.ngen . --no-cache &&/
docker build -t joshcu/ngiab-dev -f Dockerfile . --no-cache &&/
cd .. && ./guide.sh
```

In guide.sh I just ran serial and used the test data from AWI_03W_113060_001.tar.gz. Parallel also breaks at the routing step.


## Screenshot
### Serial
image
### Parallel
image

**Comment by hellkite500** [comment]
This still crashes on arm?

**Comment by JoshCu** [comment]
resolved by a series of fixes culminating in this pi #58 
related now closed issue #21

**Pull request closed without merging**
